### ISSUE TITLE
Blog strategy for Q3

### ISSUE THREAD

**Issue by mishmosh** [ipfs/blog#101]
We need to keep the blog active so people don't wonder if jpfs is dead, while balancing it with our many other goals.

Proposed strategy for Q3:
- **At least one blog post per month.** This is a pretty low bar but should be enough to feel un-dead. Previous dry spells were up to 4 months long.
- **Every ipfs release gets a blog post.** As a minimum. it will simply copy the contents of the changelog. Even better, it can share perspective on the release, thank contributors, etc. taking inspiration from [Rust](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html). _This is now part of js-ipfs release process, need to figure out how to forget-proof it for go-ipfs._
- If we need more blog posts, there are many ideas in pull requests or issues.
- Anyone with a blog post idea can contact @mishmosh who will try to work with you to ghostwrite it.
- Hold off on any redesign or re-platforming or until we "earn" it with enough blog activity to break the status quo.

(cc @lgierth @Kubuxu @flyingzumwalt)

**Comment by mishmosh** [comment]
I asked a few startup friends how they Do Good Blog in the transition between "founder is madly inspired" and "fulltime hire who maintains content calendar". The most helpful and interesting suggestion was to map out an arc of posts around certain topics, which will make us want to finish them. Just sharing as food for thought.

**Comment by flyingzumwalt** [comment]
Both js-ipfs and go-ipfs put out releases on roughly a bi-weekly cycle, so that actually gives us about 2-4 posts per month.  I think we should shoot to have one non-release post each month, on top of the release updates.

Mapping out an arc of posts for a couple topics is a great idea. I can think of a few arcs.

Some Topics to map arcs for:
- serverless search
- IPFS in web browsers
- wikipedia on IPFS, community management of data and Storing Data Together
