### ISSUE TITLE
Implement tags

### ISSUE THREAD

**Issue by autonome** [ipfs/blog#436]
We add tags to our posts' frontmatter (sometimes) but there's no implementation - no place they're actually shown on the site.

They could be visible below each post in the index page, somewhere on a post page, and many other places besides.

**Comment by jessicaschilling** [comment]
Hijacking this issue to discuss an initial taxonomy (for both post categories and post tags) to use in our blog replatforming work. @autonome and @jennwrites, your thoughts on the following? Two notes to keep in mind:
1. This is intended to be a closed taxonomy (i.e. post editors can't add new category/tags on the fly), so we want to get as close to fully defined as possible
2. Yes, I already went through past frontmatter tags for ideas 😊 

 _(cc: @Ricardo-Silva91 for awareness.)_

### Categories
- Blog posts
- Release notes
- Academic papers
- News coverage
- Videos
- Tutorials
- Events

### Tags (alphabetical)
Note: The blog will also have fulltext search, so extremely infrequent tags aren't useful; tags are mainly for purposes of cross-post discovery.
- AEgir
- Android
- API
- badger
- Bitswap
- blacklist
- blockstore
- bootstrap nodes
- breaking change
- browsers
- case study
- CDN
- CID
- CIDv0
- CIDv1
- circuit relay
- CLI tools
- collaborations
- collaborative cluster
- community
- containerization
- content routing
- CoreAPI
- CORS
- CRDTs
- DAG
- datastore
- DHT
- DNSLink
- Docker
- docs
- Drand
- ecosystem
- encryption
- Ethereum
- events
- lectures/presentations
- Filecoin
- garbage collection
- gateway
- go-ipfs
- Gossipsub
- hashing
- identity
- infrastructure
- interoperability
- IoT
- IPFS Cluster
- IPFS Companion
- IPFS Desktop
- IPFS Web UI
- IPLD
- IPNS
- js-ipfs
- Kademlia
- Kubernetes
- libp2p
- Linux
- MacOS
- MFS
- mobile
- modules
- NAT traversal
- newsletter
- npm
- offline first
- package managers
- pinning
- planning & roadmaps
- pubsub
- QUIC
- relays
- research
- Rust
- S3
- secio
- security
- specs
- static publishing
- streaming
- Testground
- tutorial
- user experience
- WebRTC
- Windows

**Comment by jennwrites** [comment]
Based on our convo this morning I put together an attempt at an abbreviated list:

* Bitswap
* blockchain
* browser
* CID
* DAG
* DHT
* event
* gossipsub
* grant
* identity
* IPLD
* IPNS
* libp2p
* mobile
* news
* OS
* pinning
* research
* security
* Testground
* tutorial

**Comment by autonome** [comment]
Initial questions and then some thoughts on the categories themselves: Why a separation of category and tag? When to use which? Should categories be exhaustive (eg no post without category)?

Re the categories:

> Blog posts

As this is for the blog... wouldn't everything fall into this category? What's the use-case?

> Release notes

Should it be just "Release", so we can use it more broadly to talk about new things we shipped?

Also, does this include partner launches like we did for Opera and ION? Or does that need a new category? Or if that's a tag, what category would it fall under?

> Academic papers
> News coverage
> Videos
> Tutorials

Do we write blog posts about these?

**Comment by jessicaschilling** [comment]
@autonome - referencing the [wireframe](https://ipfs-ia-scratchpad.netlify.app/blog-news.html) may be helpful for this.

**Categories** represent content types, since the replatformed blog uses a central "news center" metaphor to also present other items, such as papers, news items, tutorials, etc. (This model was tested both internally and externally, and very well received - can share interview notes with you if needed.) The difference between blog posts and everything else is that the blog posts live on-site in their own pages, while the other content types link off-site (or, in the case of videos, in a modal player with the option to link out to original).

Tags can be used on an item in any category. These enable organic discovery across content types, as well as aiding in search.

So, for example, the partner launch blog post for Opera would be in category `blog posts`, and tagged something like `#browsers` `#collaborations` `#ecosystem`.

**Comment by autonome** [comment]
Ahh, was thinking of this in context of the blog not all content types, so nm about the categories questions then.

**Comment by autonome** [comment]
I'm ok with casting a wide net wrt to tags - more index-ability and we will never predict all the ways in which people search.

**Comment by jessicaschilling** [comment]
Fair enough - we can always revisit in _n_ months and yank anything that we turn out not to use.

**Comment by jessicaschilling** [comment]
Closing this issue; implementation is happening in the replatform repo.
