### ISSUE TITLE
Proposal: Blog posts to announce each Release

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#97]
We all know that the blog has fallen desperately out of date. This has caused confusion, where some people think the project's activity has stopped (as evidenced in [this reddit thread](https://www.reddit.com/r/DataHoarder/comments/67lmqt/ipfs_the_internet_protocol_file_system/dgrrn5m/)), despite the fact that we're actually shipping features, optimisations and bug fixes more regularly than ever before. The confusion is exacerbated by the fact that some releases, but not all releases, have been announced in blog posts. As a result, if you only look at the blog history it looks like our last go-ipfs release was 0.4.4 on 2016-10-10 and the last js-ipfs was 0.23.0 in March. We've put out a lot of releases, with a lot of functionality, since then. go-ipfs has been on a biweekly release cycle since January. js-ipfs has had a similar cadence.

To remedy this, I propose always putting up a blog post whenever we ship a new release. A simple announcement like [the 0.23.0 announcement](https://ipfs.io/blog/23-js-ipfs-0-23/) is fine. We are already putting that info into the changelogs. Lets put it in the blog.

**Comment by flyingzumwalt** [comment]
Recently @jbenet suggested having an "ipfs tech blog" that's separate from the lower-volume official starlog. We could put the announcements there, along with posts like @whyrusleeping's [short post about pubsub](https://github.com/ipfs/blog/pull/79)

This would leave room for the main ipfs starlog to have a lower volume of high quality, polished, high profile posts while the tech blog has an informal, highly technical tone.

**Comment by lgierth** [comment]
Yeah let's post release announcements for go-ipfs and js-ipfs :+1: 

> ipfs tech blog

IMHO this is currently not warranted by the volume of either of the two, even when considering regular js-ipfs/go-ipfs release announcements. (We also want to eventually have libp2p and IPLD blogs but these are currently not warranted either.)

I'd say let's keep going with the blog until we notice there's a need to separate things. I'd hate for release announcement blog posts to be blocked right away because someone first needs to build a new blog for them.

**Comment by VictorBjelkholm** [comment]
Yay for more announcements! Had a couple of folks echo the same sentiment with project not being as active before while we keep pushing out new features and more fixes.

However, instead of splitting, I agree with @lgierth that we should have one blog and start expanding when it's necessary instead of now. I think it's better for us to have one well-maintained and often updated blog instead of five semi-active ones.

As a step in between, we could add tags/categories to the blog posts so we can separate them a bit.

**Comment by diasdavid** [comment]
here is another one that is ready to publish as soon as I npm publish :)
https://github.com/ipfs/js-ipfs/issues/855

**Comment by mishmosh** [comment]
We are halfway to resolving this issue. Blog post step has been added to js-ipfs [release checklist](https://github.com/ipfs/js-ipfs/blob/master/RELEASE.md) so it's part of the default process now.

@whyrusleeping: Is there an equivalent for go-ipfs?

**Comment by mishmosh** [comment]
I asked a few startup friends how to Do Good Blog during the transition period from "founder is madly inspired" to "person is staffed on this & maintains content calendar." The most helpful and interesting suggestion was mapping out an arc of blog posts about certain topics, so that we are motivated to finish those arcs.

**Comment by lgierth** [comment]
@mishmosh oops, in fact there's two: https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md && https://github.com/ipfs/go-ipfs/blob/master/misc/release-checklist.md

Let's keep the former and remove the latter.

**Comment by mishmosh** [comment]
Thanks @lgierth, submitted 2 PRs:
- Dedup release checklists: https://github.com/ipfs/go-ipfs/pull/3937
- Add blog to checklist: https://github.com/ipfs/go-ipfs/pull/3936

Once #3936 is merged, we can close this issue.

**Comment by mishmosh** [comment]
Done.
